apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-jrsb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-jrsb
    app.kubernetes.io/part-of: tkrw-pr714-0075-0037-app
  name: devfile-sample-jrsb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-jrsb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-jrsb
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0037-tenant/tkrw-pr714-0075-0037-app/devfile-sample-jrsb@sha256:785b61bdad16bfcfa2dd4b91d1c38246cd2536609bb96827f754e03a52a77c17
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
